spring:
    application:
        name: chat-lol
    datasource:
        url: jdbc:h2:mem:sdw2024
        drive-class-name: org.h2.Driver
        username: sa
        password: ''
    h2:
        console:
            enabled: true
            path: /h2

    jpa:
        defer-datasource-initialization: true


